thermal: fix snprintf warning
Fixes the following clang warning:

../drivers/thermal/thermal_core.c:2694:8: error: 'snprintf' size argument is too large; destination buffer has size 128, but size argument is 4096 [-Werror,-Wfortify-source]
        ret = snprintf(boost_buf, PAGE_SIZE, buf);
              ^
1 error generated.

Change-Id: I41c56cb39f0ac508fd0e54fabfc8844c64f66d09
Signed-off-by: Khusika Dhamar Gusti <mail@khusika.com>
(cherry picked from commit 074100fcf0969447d1bdd6ae2d3e0d3179b37533)